[build]
  publish = "Public"

[[headers]]
  for = "/*.bin"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"

[[headers]]
  for = "/model.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"